eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8004

spring:
  application:
    name: r-project-user

  datasource:
    url: jdbc:mysql://localhost:3307/JLCredit  #连接user数据库
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 0 #redis索引
    host: localhost #redis服务器地址
    port: 6379 #端口号
    password:  #链接密码
    timeout: 3000 #超时时间（毫秒）
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1 #最大阻塞等待时间
        max-idle: 10 #最大空闲时间
        min-idle: 0 #最小空闲时间