server:
  port: 8012
spring:
  application:
    name: r-project-consul

  cloud:
    consul: #consul 注册
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
