server:
  port: 8014

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


spring:
  application:
    name: rf-project-oauth2service
  redis:
    host: localhost
    port: 6379
    timeout: 36000 #设置过期时间

  security:
    user:
      name: 123
      password: 123
