server:
  port: 8008

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: r-project-sqls
  datasource:
    jlcredit:
      jdbc-url: jdbc:mysql://localhost:3307/JLCredit  #连接数据库
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    log:
      jdbc-url: jdbc:mysql://localhost:3307/log  #连接数据库
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

  #    shop:
  #      url: jdbc:mysql://localhost:3307/shop  #连接数据库
  #      username: root
  #      password: 123456
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      jlcredit-dialect: org.hibernate.dialect.MySQL5Dialect
      log-dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true


