server:
  port: 8015

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


spring:
  application:
    name: rf-project-oauth2client

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8014/oauth/user
    client:
      client-id: webapp
      client-secret: secret
      access-token-uri: http://localhost:8014/oauth/token
      user-authorization-uri: http://localhost:8014/oauth/authorize



