eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8003

spring:
  application:
    name: r-project-zuul
  redis:
    host: localhost
    port: 6379
    timeout: 36000 #设置过期时间

#zuul的包中已经导入了熔断机制



#zuul网关代理服务
zuul:
  ignoredServices: '*' #忽略所有未配置的service

  routes:
    test:
      path: /test/**
      serviceId: r-project-test  #module test1余test2 做负载均衡 只要项目name一致

    article:
      path: /article/**
      serviceId: r-project-article



