eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8003

spring:
  application:
    name: r-project-zuul
  redis:
    host: localhost
    port: 6379
    timeout: 36000 #设置过期时间

logging:
  config: classpath:logback-spring.xml
#  file:
#    max-history: 10
#  #生成日志文件并且保存在该地址
#  path:  /Users/ruanchenhao/log



#zuul网关代理服务
zuul:
  ignoredServices: '*' #忽略所有未配置的service
  routes:
    test:
      path: /test/**
      serviceId: r-project-test  #module test1余test2 做负载均衡 只要项目name一致

    article:
      path: /article/**
      serviceId: r-project-article


  #网关配置限流的工具
  ratelimit:
    enabled: true #启用限流
    behind-proxy: true #在代理之后
    repository: redis #储存类型
    key-prefix: r-project-zuul #储存key的前缀
    default-policy: #全局限流策略 3秒内不超过2次，两次请求时间要小于1秒
      limit: 2
      quota: 1
      refresh-interval: 3

    #对于test服务的特殊限流配置
    policies:
      test:  #10秒内请求次数不能超过5次，这5次请求时间总时长不能大于5s
      limit: 5
      quota: 5
      efresh-interval: 10







