server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  application:
    name: r-project-config
  cloud:
    config:
      server:
        default-application-name: r-project-config
        git:
          uri: https://github.com/ladyishenlong/project-r/tree/master/cloud-config
          search-paths: testconfig
          default-label: master

          #公开仓库可以不填
#          username:
#          password:







