server:
  port: 8010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/


spring:
  application:
    name: r-project-config
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      server:
        default-application-name: r-project-config
        git:
          #项目地址
          uri: https://github.com/ladyishenlong/project-r
          search-paths: cloud-config
          default-label: master

          #公开仓库可以不填
          #          username:
          #          password:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin


management:
  endpoints:
    web:
      exposure:
        include: bus-refresh




